# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IBMCFCShizen01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IBMCFCShizen01
  pod 'Alamofire', '4.9.1'

  target 'IBMCFCShizen01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IBMCFCShizen01UITests' do
    # Pods for testing
  end

end
